//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuotableQuotations.Client.QuotableQuotationsReliableWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotableQuotation", Namespace="http://schemas.datacontract.org/2004/07/QuotableQuotations.Contracts.Classes")]
    [System.SerializableAttribute()]
    public partial class QuotableQuotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quote {
            get {
                return this.QuoteField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoteField, value) != true)) {
                    this.QuoteField = value;
                    this.RaisePropertyChanged("Quote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuotableQuotationsReliableWcfService.IQuotableQuotationsReliableWcfService")]
    public interface IQuotableQuotationsReliableWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuotableQuotationsReliableWcfService/UpdateOrInsertQuotations" +
            "", ReplyAction="http://tempuri.org/IQuotableQuotationsReliableWcfService/UpdateOrInsertQuotations" +
            "Response")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void UpdateOrInsertQuotations(QuotableQuotations.Client.QuotableQuotationsReliableWcfService.QuotableQuotation[] quotableQuotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuotableQuotationsReliableWcfService/UpdateOrInsertQuotations" +
            "", ReplyAction="http://tempuri.org/IQuotableQuotationsReliableWcfService/UpdateOrInsertQuotations" +
            "Response")]
        System.Threading.Tasks.Task UpdateOrInsertQuotationsAsync(QuotableQuotations.Client.QuotableQuotationsReliableWcfService.QuotableQuotation[] quotableQuotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuotableQuotationsReliableWcfService/DeleteQuotations", ReplyAction="http://tempuri.org/IQuotableQuotationsReliableWcfService/DeleteQuotationsResponse" +
            "")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void DeleteQuotations(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuotableQuotationsReliableWcfService/DeleteQuotations", ReplyAction="http://tempuri.org/IQuotableQuotationsReliableWcfService/DeleteQuotationsResponse" +
            "")]
        System.Threading.Tasks.Task DeleteQuotationsAsync(int[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuotableQuotationsReliableWcfServiceChannel : QuotableQuotations.Client.QuotableQuotationsReliableWcfService.IQuotableQuotationsReliableWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotableQuotationsReliableWcfServiceClient : System.ServiceModel.ClientBase<QuotableQuotations.Client.QuotableQuotationsReliableWcfService.IQuotableQuotationsReliableWcfService>, QuotableQuotations.Client.QuotableQuotationsReliableWcfService.IQuotableQuotationsReliableWcfService {
        
        public QuotableQuotationsReliableWcfServiceClient() {
        }
        
        public QuotableQuotationsReliableWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotableQuotationsReliableWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotableQuotationsReliableWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotableQuotationsReliableWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateOrInsertQuotations(QuotableQuotations.Client.QuotableQuotationsReliableWcfService.QuotableQuotation[] quotableQuotations) {
            base.Channel.UpdateOrInsertQuotations(quotableQuotations);
        }
        
        public System.Threading.Tasks.Task UpdateOrInsertQuotationsAsync(QuotableQuotations.Client.QuotableQuotationsReliableWcfService.QuotableQuotation[] quotableQuotations) {
            return base.Channel.UpdateOrInsertQuotationsAsync(quotableQuotations);
        }
        
        public void DeleteQuotations(int[] ids) {
            base.Channel.DeleteQuotations(ids);
        }
        
        public System.Threading.Tasks.Task DeleteQuotationsAsync(int[] ids) {
            return base.Channel.DeleteQuotationsAsync(ids);
        }
    }
}
